name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c release -r debian.10-x64 --self-contained
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy with rsync
      run: rsync -av ~/work/GoogleDiscordBot/GoogleDiscordBot/GoogleBot/bin/Release/net6.0/debian.10-x64/publish/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/worker/GoogleDiscordBot/publish

    - name: Trigger Bot Restart
      id: req
      uses: fjogeleit/http-request-action@master
      with:
        url: https://api.taptwice.dev/services/discord-bot/restart?key=${{secretes.API_KEY_SERVICES}}
        method: "GET"
        run: echo ${{ steps.req.outputs.response }}
        
